### ISSUE TITLE
Mobile safari

### ISSUE THREAD

**Issue by tifroz** [egonelbre/jsfx#1]
This is really pretty awesome...I had no idea javascript could be use to emit sounds to begin with!

I couldn't get any sound out of it on mobile safari though (running on the iPhone) - any idea why and if that's something that could be addressed? (Yes...I check that the volume was turned up all the way)

Either way - thanks a lot for sharing, it's very impressive.

**Comment by egonelbre** [comment]
I re-tested this with Safari/600.1.4 on iOS 8.3 and it seems to be working now.
