### ISSUE TITLE
Callbacks / Custom events on audio ready?

### ISSUE THREAD

**Issue by hay** [egonelbre/jsfx#3]
I'm wondering, when generating a lot of sounds (25 or so) it can take up a few seconds before everything is loaded. Not quite sure why. However, would it be possible somehow to get pass a callback parameter on creation that is called when the sound is ready so you can display a loading animation? I've looked in the source code but can't quite figure out how to do that...

**Comment by egonelbre** [comment]
Closing due to no response.
